/*
 Copyright 2025 Google LLC

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      https://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/

/**
 * A map of Google Ads language constant IDs to their corresponding language names.
 */
export const GOOGLE_ADS_LANGUAGE_MAP: Record<string, string> = {
  'languageConstants/1000': 'English',
  'languageConstants/1001': 'German',
  'languageConstants/1002': 'French',
  'languageConstants/1003': 'Spanish',
  'languageConstants/1004': 'Italian',
  'languageConstants/1005': 'Japanese',
  'languageConstants/1006': 'Danish',
  'languageConstants/1007': 'Dutch',
  'languageConstants/1008': 'Finnish',
  'languageConstants/1009': 'Norwegian',
  'languageConstants/1010': 'Portuguese',
  'languageConstants/1011': 'Swedish',
  'languageConstants/1012': 'Chinese (Simplified)',
  'languageConstants/1013': 'Russian',
  'languageConstants/1014': 'Korean',
  'languageConstants/1015': 'Arabic',
  'languageConstants/1016': 'Hebrew',
  'languageConstants/1017': 'Chinese (Traditional)',
  'languageConstants/1018': 'Greek',
  'languageConstants/1019': 'Polish',
  'languageConstants/1020': 'Thai',
  'languageConstants/1021': 'Turkish',
  'languageConstants/1022': 'Indonesian',
  'languageConstants/1023': 'Vietnamese',
  'languageConstants/1024': 'Czech',
  'languageConstants/1025': 'Hungarian',
  'languageConstants/1026': 'Romanian',
  'languageConstants/1027': 'Hindi',
  'languageConstants/1028': 'Ukrainian',
  'languageConstants/1029': 'Slovak',
  'languageConstants/1030': 'Bulgarian',
  'languageConstants/1031': 'Croatian',
  'languageConstants/1032': 'Lithuanian',
  'languageConstants/1033': 'Slovenian',
  'languageConstants/1034': 'Latvian',
  'languageConstants/1035': 'Estonian',
  'languageConstants/1036': 'Serbian',
  'languageConstants/1037': 'Filipino',
  'languageConstants/1038': 'Icelandic',
  'languageConstants/1039': 'Malay',
  'languageConstants/1040': 'Persian',
  'languageConstants/1041': 'Urdu',
  'languageConstants/1042': 'Bengali',
  'languageConstants/1043': 'Gujarati',
  'languageConstants/1044': 'Kannada',
  'languageConstants/1045': 'Malayalam',
  'languageConstants/1046': 'Marathi',
  'languageConstants/1047': 'Punjabi',
  'languageConstants/1048': 'Tamil',
  'languageConstants/1049': 'Telugu',
};

/**
 * A map of Google Ads geo target constant IDs to their corresponding location names.
 */
export const GOOGLE_ADS_GEO_TARGET_MAP: Record<string, string> = {
  'geoTargetConstants/2840': 'United States',
  'geoTargetConstants/2250': 'France',
  'geoTargetConstants/2276': 'Germany',
  'geoTargetConstants/2380': 'Japan',
  'geoTargetConstants/2826': 'United Kingdom',
  'geoTargetConstants/2036': 'Australia',
  'geoTargetConstants/2124': 'Canada',
  'geoTargetConstants/2076': 'Brazil',
  'geoTargetConstants/2356': 'India',
  'geoTargetConstants/2360': 'Indonesia',
  'geoTargetConstants/2392': 'Italy',
  'geoTargetConstants/2484': 'Mexico',
  'geoTargetConstants/2528': 'Netherlands',
  'geoTargetConstants/2643': 'Russia',
  'geoTargetConstants/2702': 'Saudi Arabia',
  'geoTargetConstants/2710': 'South Africa',
  'geoTargetConstants/2410': 'South Korea',
  'geoTargetConstants/2724': 'Spain',
  'geoTargetConstants/2752': 'Sweden',
  'geoTargetConstants/2756': 'Switzerland',
  'geoTargetConstants/2792': 'Turkey',
  'geoTargetConstants/2004': 'Afghanistan',
  'geoTargetConstants/2008': 'Albania',
  'geoTargetConstants/2012': 'Algeria',
  'geoTargetConstants/2020': 'Andorra',
  'geoTargetConstants/2024': 'Angola',
  'geoTargetConstants/2028': 'Antigua and Barbuda',
  'geoTargetConstants/2032': 'Argentina',
  'geoTargetConstants/2051': 'Armenia',
  'geoTargetConstants/2040': 'Austria',
  'geoTargetConstants/2031': 'Azerbaijan',
  'geoTargetConstants/2044': 'Bahamas',
  'geoTargetConstants/2048': 'Bahrain',
  'geoTargetConstants/2050': 'Bangladesh',
  'geoTargetConstants/2052': 'Barbados',
  'geoTargetConstants/2112': 'Belarus',
  'geoTargetConstants/2056': 'Belgium',
  'geoTargetConstants/2084': 'Belize',
  'geoTargetConstants/2204': 'Benin',
  'geoTargetConstants/2064': 'Bhutan',
  'geoTargetConstants/2068': 'Bolivia',
  'geoTargetConstants/2070': 'Bosnia and Herzegovina',
  'geoTargetConstants/2072': 'Botswana',
  'geoTargetConstants/2092': 'British Virgin Islands',
  'geoTargetConstants/2096': 'Brunei',
  'geoTargetConstants/2100': 'Bulgaria',
  'geoTargetConstants/2854': 'Burkina Faso',
  'geoTargetConstants/2108': 'Burundi',
  'geoTargetConstants/2132': 'Cabo Verde',
  'geoTargetConstants/2116': 'Cambodia',
  'geoTargetConstants/2120': 'Cameroon',
  'geoTargetConstants/2140': 'Central African Republic',
  'geoTargetConstants/2148': 'Chad',
  'geoTargetConstants/2152': 'Chile',
  'geoTargetConstants/2156': 'China',
  'geoTargetConstants/2170': 'Colombia',
  'geoTargetConstants/2174': 'Comoros',
  'geoTargetConstants/2178': 'Congo (Brazzaville)',
  'geoTargetConstants/2180': 'Congo (Kinshasa)',
  'geoTargetConstants/2184': 'Cook Islands',
  'geoTargetConstants/2188': 'Costa Rica',
  'geoTargetConstants/2384': 'Cote d\'Ivoire',
  'geoTargetConstants/2191': 'Croatia',
  'geoTargetConstants/2196': 'Cyprus',
  'geoTargetConstants/2203': 'Czechia',
  'geoTargetConstants/2208': 'Denmark',
  'geoTargetConstants/2262': 'Djibouti',
  'geoTargetConstants/2212': 'Dominica',
  'geoTargetConstants/2214': 'Dominican Republic',
  'geoTargetConstants/2218': 'Ecuador',
  'geoTargetConstants/2818': 'Egypt',
  'geoTargetConstants/2222': 'El Salvador',
  'geoTargetConstants/2226': 'Equatorial Guinea',
  'geoTargetConstants/2232': 'Eritrea',
  'geoTargetConstants/2233': 'Estonia',
  'geoTargetConstants/2748': 'Eswatini',
  'geoTargetConstants/2231': 'Ethiopia',
  'geoTargetConstants/2242': 'Fiji',
  'geoTargetConstants/2246': 'Finland',
  'geoTargetConstants/2266': 'Gabon',
  'geoTargetConstants/2270': 'Gambia',
  'geoTargetConstants/2268': 'Georgia',
  'geoTargetConstants/2288': 'Ghana',
  'geoTargetConstants/2300': 'Greece',
  'geoTargetConstants/2308': 'Grenada',
  'geoTargetConstants/2320': 'Guatemala',
  'geoTargetConstants/2324': 'Guinea',
  'geoTargetConstants/2624': 'Guinea-Bissau',
  'geoTargetConstants/2328': 'Guyana',
  'geoTargetConstants/2332': 'Haiti',
  'geoTargetConstants/2340': 'Honduras',
  'geoTargetConstants/2344': 'Hong Kong',
  'geoTargetConstants/2348': 'Hungary',
  'geoTargetConstants/2352': 'Iceland',
  'geoTargetConstants/2368': 'Iraq',
  'geoTargetConstants/2372': 'Ireland',
  'geoTargetConstants/2376': 'Israel',
  'geoTargetConstants/2388': 'Jamaica',
  'geoTargetConstants/2400': 'Jordan',
  'geoTargetConstants/2398': 'Kazakhstan',
  'geoTargetConstants/2404': 'Kenya',
  'geoTargetConstants/2296': 'Kiribati',
  'geoTargetConstants/2417': 'Kosovo',
  'geoTargetConstants/2414': 'Kuwait',
  'geoTargetConstants/2418': 'Kyrgyzstan',
  'geoTargetConstants/2428': 'Latvia',
  'geoTargetConstants/2422': 'Laos',
  'geoTargetConstants/2434': 'Lebanon',
  'geoTargetConstants/2426': 'Lesotho',
  'geoTargetConstants/2430': 'Liberia',
  'geoTargetConstants/2438': 'Libya',
  'geoTargetConstants/2440': 'Liechtenstein',
  'geoTargetConstants/2442': 'Lithuania',
  'geoTargetConstants/2446': 'Luxembourg',
  'geoTargetConstants/2450': 'Madagascar',
  'geoTargetConstants/2454': 'Malawi',
  'geoTargetConstants/2458': 'Malaysia',
  'geoTargetConstants/2462': 'Maldives',
  'geoTargetConstants/2466': 'Mali',
  'geoTargetConstants/2470': 'Malta',
  'geoTargetConstants/2584': 'Marshall Islands',
  'geoTargetConstants/2478': 'Mauritania',
  'geoTargetConstants/2480': 'Mauritius',
  'geoTargetConstants/2175': 'Mayotte',
  'geoTargetConstants/2583': 'Micronesia',
  'geoTargetConstants/2498': 'Moldova',
  'geoTargetConstants/2492': 'Monaco',
  'geoTargetConstants/2496': 'Mongolia',
  'geoTargetConstants/2499': 'Montenegro',
  'geoTargetConstants/2504': 'Morocco',
  'geoTargetConstants/2508': 'Mozambique',
  'geoTargetConstants/2104': 'Myanmar',
  'geoTargetConstants/2516': 'Namibia',
  'geoTargetConstants/2520': 'Nauru',
  'geoTargetConstants/2524': 'Nepal',
  'geoTargetConstants/2554': 'New Zealand',
  'geoTargetConstants/2558': 'Nicaragua',
  'geoTargetConstants/2562': 'Niger',
  'geoTargetConstants/2566': 'Nigeria',
  'geoTargetConstants/2570': 'North Macedonia',
  'geoTargetConstants/2578': 'Norway',
  'geoTargetConstants/2512': 'Oman',
  'geoTargetConstants/2586': 'Pakistan',
  'geoTargetConstants/2585': 'Palau',
  'geoTargetConstants/2275': 'Palestine',
  'geoTargetConstants/2591': 'Panama',
  'geoTargetConstants/2598': 'Papua New Guinea',
  'geoTargetConstants/2600': 'Paraguay',
  'geoTargetConstants/2604': 'Peru',
  'geoTargetConstants/2608': 'Philippines',
  'geoTargetConstants/2616': 'Poland',
  'geoTargetConstants/2620': 'Portugal',
  'geoTargetConstants/2634': 'Qatar',
  'geoTargetConstants/2642': 'Romania',
  'geoTargetConstants/2646': 'Rwanda',
  'geoTargetConstants/2654': 'Saint Kitts and Nevis',
  'geoTargetConstants/2662': 'Saint Lucia',
  'geoTargetConstants/2670': 'Saint Vincent and the Grenadines',
  'geoTargetConstants/2882': 'Samoa',
  'geoTargetConstants/2674': 'San Marino',
  'geoTargetConstants/2678': 'Sao Tome and Principe',
  'geoTargetConstants/2682': 'Senegal',
  'geoTargetConstants/2688': 'Serbia',
  'geoTargetConstants/2690': 'Seychelles',
  'geoTargetConstants/2694': 'Sierra Leone',
  'geoTargetConstants/2700': 'Singapore',
  'geoTargetConstants/2703': 'Slovakia',
  'geoTargetConstants/2705': 'Slovenia',
  'geoTargetConstants/2090': 'Solomon Islands',
  'geoTargetConstants/2706': 'Somalia',
  'geoTargetConstants/2728': 'South Sudan',
  'geoTargetConstants/2144': 'Sri Lanka',
  'geoTargetConstants/2736': 'Sudan',
  'geoTargetConstants/2740': 'Suriname',
  'geoTargetConstants/2760': 'Syria',
  'geoTargetConstants/2158': 'Taiwan',
  'geoTargetConstants/2762': 'Tajikistan',
  'geoTargetConstants/2834': 'Tanzania',
  'geoTargetConstants/2764': 'Thailand',
  'geoTargetConstants/2626': 'Timor-Leste',
  'geoTargetConstants/2768': 'Togo',
  'geoTargetConstants/2776': 'Tonga',
  'geoTargetConstants/2780': 'Trinidad and Tobago',
  'geoTargetConstants/2788': 'Tunisia',
  'geoTargetConstants/2795': 'Turkmenistan',
  'geoTargetConstants/2798': 'Tuvalu',
  'geoTargetConstants/2800': 'Uganda',
  'geoTargetConstants/2804': 'Ukraine',
  'geoTargetConstants/2784': 'United Arab Emirates',
  'geoTargetConstants/2858': 'Uruguay',
  'geoTargetConstants/2860': 'Uzbekistan',
  'geoTargetConstants/2548': 'Vanuatu',
  'geoTargetConstants/2862': 'Venezuela',
  'geoTargetConstants/2704': 'Vietnam',
  'geoTargetConstants/2887': 'Yemen',
  'geoTargetConstants/2894': 'Zambia',
  'geoTargetConstants/2716': 'Zimbabwe',
};
